/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WishListImport } from './routes/wish-list'
import { Route as MessageImport } from './routes/message'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WishListRoute = WishListImport.update({
  id: '/wish-list',
  path: '/wish-list',
  getParentRoute: () => rootRoute,
} as any)

const MessageRoute = MessageImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/message': {
      id: '/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof MessageImport
      parentRoute: typeof rootRoute
    }
    '/wish-list': {
      id: '/wish-list'
      path: '/wish-list'
      fullPath: '/wish-list'
      preLoaderRoute: typeof WishListImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/message': typeof MessageRoute
  '/wish-list': typeof WishListRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/message': typeof MessageRoute
  '/wish-list': typeof WishListRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/message': typeof MessageRoute
  '/wish-list': typeof WishListRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/message' | '/wish-list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/message' | '/wish-list'
  id: '__root__' | '/' | '/message' | '/wish-list'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MessageRoute: typeof MessageRoute
  WishListRoute: typeof WishListRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MessageRoute: MessageRoute,
  WishListRoute: WishListRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/message",
        "/wish-list"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/message": {
      "filePath": "message.jsx"
    },
    "/wish-list": {
      "filePath": "wish-list.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
